#!/usr/bin/env bash
# =============================================================================
# run-in-plasma-session.sh -- execute a command INSIDE the live graphical
# Plasma session of the interactive desktop user.
#
# Hermes may be started from systemd --user / a lingering unit / a plain shell,
# so its own environment is NOT authoritative. The live plasmashell process is:
# its /proc/<pid>/environ is the authoritative source of the graphical + audio
# session variables.
#
# USAGE
#   run-in-plasma-session.sh refresh-env          # discover session, write plasma-session.env
#   run-in-plasma-session.sh show-env             # print the discovered variables
#   run-in-plasma-session.sh <cmd> [args...]      # run cmd with the recovered env
#
# SAFETY / HONESTY RULES
#   * only a small allow-list of variables is copied - never the whole environ
#   * no secret-looking variable is written to plasma-session.env or to the log
#   * an exit code of 0 DOES NOT prove that a window became visible or that a
#     sound was audible. GUI/audio success needs a screenshot or the operator's
#     confirmation; this script never claims otherwise.
# =============================================================================
set -uo pipefail

LAB_ROOT="${LAB_ROOT:-/home/salamanka/armorx-lab}"
ENV_FILE="$LAB_ROOT/automation/plasma-session.env"
LOG="$LAB_ROOT/logs/run-in-plasma-session.log"
DESKTOP_USER="${ARMORX_DESKTOP_USER:-salamanka}"

# Allow-list only. PATH is kept because GUI launchers need it, nothing else large.
SAFE_VARS=(
  DISPLAY WAYLAND_DISPLAY DBUS_SESSION_BUS_ADDRESS XDG_RUNTIME_DIR XAUTHORITY
  HOME USER LOGNAME PATH PULSE_SERVER PIPEWIRE_REMOTE
  XDG_SESSION_TYPE XDG_CURRENT_DESKTOP KDE_FULL_SESSION XDG_SESSION_ID
)

mkdir -p "$(dirname "$LOG")"
log() { printf '%s %s\n' "$(date -Is)" "$*" >>"$LOG"; }

# --- 1. resolve the LIVE plasma pid (never assumed, always re-resolved) -------
PLASMA_PID=""
PLASMA_PROC=""
resolve_plasma_pid() {
  local name p
  PLASMA_PID=""; PLASMA_PROC=""
  for name in plasmashell kwin_wayland kwin_x11 ksmserver; do
    p="$(pgrep -u "$DESKTOP_USER" -x "$name" 2>/dev/null | head -1)"
    if [ -n "${p:-}" ]; then PLASMA_PID="$p"; PLASMA_PROC="$name"; return 0; fi
  done
  return 1
}

# --- 2. read the allow-listed variables out of that process ------------------
declare -A SESSION_VARS=()
read_session_vars() {
  SESSION_VARS=()
  local env_dump v val
  [ -r "/proc/$PLASMA_PID/environ" ] || return 1
  env_dump="$(tr '\0' '\n' < "/proc/$PLASMA_PID/environ" 2>/dev/null)" || return 1
  for v in "${SAFE_VARS[@]}"; do
    val="$(printf '%s\n' "$env_dump" | sed -n "s/^$v=//p" | head -1)"
    [ -n "${val:-}" ] && SESSION_VARS["$v"]="$val"
  done
  # sensible fallbacks, never guessed from a different user
  : "${SESSION_VARS[XDG_RUNTIME_DIR]:=/run/user/$(id -u)}"
  if [ -z "${SESSION_VARS[DBUS_SESSION_BUS_ADDRESS]:-}" ] \
     && [ -S "${SESSION_VARS[XDG_RUNTIME_DIR]}/bus" ]; then
    SESSION_VARS[DBUS_SESSION_BUS_ADDRESS]="unix:path=${SESSION_VARS[XDG_RUNTIME_DIR]}/bus"
  fi
  return 0
}

# --- 3. validate the recovered session ---------------------------------------
VALIDATION_FAILED=0
validate_session() {
  local rt
  VALIDATION_FAILED=0
  # plasma pid must belong to the desktop user
  if [ "$(stat -c '%U' "/proc/$PLASMA_PID" 2>/dev/null)" != "$DESKTOP_USER" ]; then
    echo "VALIDATION FAIL: /proc/$PLASMA_PID not owned by $DESKTOP_USER" >&2; VALIDATION_FAILED=1
  fi
  rt="${SESSION_VARS[XDG_RUNTIME_DIR]:-}"
  if [ -z "$rt" ] || [ "$(stat -c '%U' "$rt" 2>/dev/null)" != "$DESKTOP_USER" ]; then
    echo "VALIDATION FAIL: XDG_RUNTIME_DIR '$rt' not owned by $DESKTOP_USER" >&2; VALIDATION_FAILED=1
  fi
  if [ ! -S "$rt/bus" ]; then
    echo "VALIDATION FAIL: session DBus socket $rt/bus missing" >&2; VALIDATION_FAILED=1
  fi
  if [ -z "${SESSION_VARS[DISPLAY]:-}" ] && [ -z "${SESSION_VARS[WAYLAND_DISPLAY]:-}" ]; then
    echo "VALIDATION FAIL: neither DISPLAY nor WAYLAND_DISPLAY" >&2; VALIDATION_FAILED=1
  fi
  # session must be active according to logind
  if command -v loginctl >/dev/null 2>&1; then
    local sid state
    for sid in $(loginctl list-sessions --no-legend 2>/dev/null | awk -v u="$DESKTOP_USER" '$3==u {print $1}'); do
      state="$(loginctl show-session "$sid" -p State --value 2>/dev/null)"
      if [ "$state" = "active" ] && loginctl show-session "$sid" -p Active --value 2>/dev/null | grep -q yes; then
        return 0
      fi
    done
    echo "VALIDATION WARN: no logind session reported active for $DESKTOP_USER" >&2
  fi
}

# --- 4. write the env file (0600) --------------------------------------------
write_env_file() {
  local tmp v
  tmp="$(mktemp)"
  {
    echo "# generated by run-in-plasma-session.sh at $(date -Is)"
    echo "# source process: $PLASMA_PROC pid=$PLASMA_PID user=$DESKTOP_USER"
    for v in "${SAFE_VARS[@]}"; do
      [ -n "${SESSION_VARS[$v]:-}" ] || continue
      printf '%s=%q\n' "$v" "${SESSION_VARS[$v]}"
    done
    # the wrapper needs these too when the Plasma process does not export them
    printf '%s=%q\n' XDG_RUNTIME_DIR "${SESSION_VARS[XDG_RUNTIME_DIR]}"
    printf '%s=%q\n' DBUS_SESSION_BUS_ADDRESS "${SESSION_VARS[DBUS_SESSION_BUS_ADDRESS]:-}"
  } >"$tmp"
  install -m 0600 "$tmp" "$ENV_FILE"
  rm -f "$tmp"
}

# --- 5. load the env into this shell ------------------------------------------
load_env() {
  # shellcheck disable=SC1090
  [ -f "$ENV_FILE" ] && . "$ENV_FILE"
}

refresh() {
  if ! resolve_plasma_pid; then
    echo "ERROR: no live Plasma process found for $DESKTOP_USER" >&2
    log "refresh FAILED: no plasma process for $DESKTOP_USER"
    return 1
  fi
  read_session_vars || { echo "ERROR: cannot read /proc/$PLASMA_PID/environ" >&2; return 1; }
  validate_session
  write_env_file
  log "refresh ok: proc=$PLASMA_PROC pid=$PLASMA_PID display=${SESSION_VARS[DISPLAY]:-none} wayland=${SESSION_VARS[WAYLAND_DISPLAY]:-none} runtime=${SESSION_VARS[XDG_RUNTIME_DIR]:-none}"
  return 0
}

show_env() {
  load_env
  echo "plasma process : $PLASMA_PROC pid=$PLASMA_PID user=$DESKTOP_USER"
  local v
  for v in DISPLAY WAYLAND_DISPLAY DBUS_SESSION_BUS_ADDRESS XDG_RUNTIME_DIR XAUTHORITY HOME USER LOGNAME; do
    printf '%-28s %s\n' "$v" "${!v:-<absent>}"
  done
  printf '%-28s %s\n' PATH "(len ${#PATH})"
}

case "${1:-}" in
  refresh-env) shift; refresh ;;
  show-env)    shift; show_env ;;
  ""|-h|--help) sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'; exit 2 ;;
  *)
    # every invocation re-resolves the live Plasma pid and refreshes the vars
    refresh >/dev/null || { echo "run-in-plasma-session: session refresh failed" >&2; exit 1; }
    load_env
    export DISPLAY WAYLAND_DISPLAY DBUS_SESSION_BUS_ADDRESS XDG_RUNTIME_DIR XAUTHORITY
    log "run: $* (exit code is NOT proof of visual/audible success)"
    "$@"
    rc=$?
    log "run rc=$rc: $*"
    exit $rc
    ;;
esac
